permissions:
  contents: read

jobs:
   snyk:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Snyk CLI to check for security issues
        uses: actions/setup-node@v4
        with:
           node-version: 20
      - uses: snyk/actions/setup@cdb760004ba9ea4d525f2e043745dfe85bb9077e
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Snyk Code test
        run: snyk auth --auth-type=token  ${{ secrets.SNYK_TOKEN }} && snyk test  --sarif > snyk-code.sarif  || true
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.5.0
        with:
    # Artifact name
            name: code # optional, default is artifact
    # A file, directory or wildcard pattern that describes what to upload
            path: snyk-code.sarif
    # The desired behavior if no files are found using the provided path.


        # Runs Snyk Infrastructure as Code (IaC) analysis and uploads result to Snyk.
        # Use || true to not fail the pipeline.
     
      - name: Upload result to GitHub Code Scanning
        uses: pixee/upload-tool-results-action@v2
        with:
          tool: 'snyk'
          file: snyk-code.sarif